[package]
name = "buffer"
version = "0.1.1"
authors = ["Tobias Bucher <tobiasbucher5991@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tbu-/buffer"
description = "Safe, write-only, generics-free buffer abstraction"

[dependencies]
arrayvec = "0.3.16"
mac = "0.0.2"
